### linter back
_lint-back: &lint-back
  os: linux
  sudo: required
  services: docker
  cache:
  install:
    - sudo sysctl -w vm.max_map_count=262144
  script:
    - ls -la

### linter front
_lint-front: &lint-front
  os: linux
  sudo: required
  services: docker
  cache:
  install:
    - sudo sysctl -w vm.max_map_count=262144
  script:
    - ls -la

### unit tests avec Mocha
_unit-tests: &unit-tests
  os: linux
  sudo: required
  services: docker
  cache:
  install:
    - sudo sysctl -w vm.max_map_count=262144
  script:
    - ls -la


### e2e tests avec Cypress
_functional-tests: &functional-tests
  os: linux
  sudo: required
  services: docker
  script:
    - ls -la


### Deploy sur dockerhub
_docker-image-deploy: &docker-image-deploy
  stage: Deployments images docker
  language: minimal
  services: docker
  if: type=push AND branch=master
  script:
    - cd backend
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build . -t $IMAGE_NAME
    - docker push $IMAGE_NAME:latest

jobs:
  include:
    - <<: *lint-back
      stage: lint-back
      name: lint-back

    - <<: *lint-front
      stage: lint-front
      name: lint-front

    - <<: *unit-tests
      stage: Unit tests
      name: Unit Tests

    - <<: *e2e-tests
      stage: e2e tests
      name: e2e tests

    - <<: *docker-image-deploy
      stage: Deployments images docker
      name: Deployment% images docker
