version: '2.1'
services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "5005:5005"
    depends_on:
        postgresql:
          condition: "service_healthy"

  postgresql:
    image: postgres:9.6.2-alpine
    volumes:
      - ./postgresql-dump:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: "/usr/bin/postgresql --user=root --password=root --execute \"\\d;\""
      interval: 2s
      timeout: 40s
      retries: 20